import os
import shutil
import ssl
import tempfile
import unittest

try:
    import cryptography  # noqa: F401
    HAS_CRYPTOGRAPHY = True
except ImportError:
    HAS_CRYPTOGRAPHY = False

if HAS_CRYPTOGRAPHY:
    from ovos_messagebus.ssl_utils import create_self_signed_cert


@unittest.skipUnless(HAS_CRYPTOGRAPHY, "cryptography (pyopenssl extra) not installed")
class TestCreateSelfSignedCert(unittest.TestCase):
    def setUp(self):
        self.cert_dir = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.cert_dir, ignore_errors=True)

    def test_generates_usable_cert_and_key(self):
        """The generated pair must actually load into an SSLContext.

        This is the regression check for the EE_KEY_TOO_SMALL class of bug:
        a 1024-bit RSA / SHA-1 pair (as generated by the now-removed
        ovos_utils.security.create_self_signed_cert) is rejected outright by
        OpenSSL 3's default security level.
        """
        cert_path, key_path = create_self_signed_cert(self.cert_dir, name="test-bus")

        self.assertTrue(os.path.isfile(cert_path))
        self.assertTrue(os.path.isfile(key_path))

        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        ctx.load_cert_chain(cert_path, key_path)  # raises if unusable

    def test_key_size_is_at_least_2048_bits(self):
        from cryptography.hazmat.primitives import serialization

        cert_path, key_path = create_self_signed_cert(self.cert_dir, name="test-bus")
        with open(key_path, "rb") as f:
            key = serialization.load_pem_private_key(f.read(), password=None)
        self.assertGreaterEqual(key.key_size, 2048)

    def test_san_covers_localhost_and_hostname(self):
        from socket import gethostname
        from cryptography import x509

        cert_path, _ = create_self_signed_cert(self.cert_dir, name="test-bus")
        with open(cert_path, "rb") as f:
            cert = x509.load_pem_x509_certificate(f.read())

        san_ext = cert.extensions.get_extension_for_class(x509.SubjectAlternativeName)
        dns_names = san_ext.value.get_values_for_type(x509.DNSName)
        ip_addresses = [str(ip) for ip in san_ext.value.get_values_for_type(x509.IPAddress)]

        self.assertIn("localhost", dns_names)
        self.assertIn(gethostname(), dns_names)
        self.assertIn("127.0.0.1", ip_addresses)

    def test_reuses_existing_pair_instead_of_regenerating(self):
        cert_path, key_path = create_self_signed_cert(self.cert_dir, name="test-bus")
        with open(cert_path, "rb") as f:
            first_cert_bytes = f.read()
        with open(key_path, "rb") as f:
            first_key_bytes = f.read()

        cert_path_2, key_path_2 = create_self_signed_cert(self.cert_dir, name="test-bus")

        self.assertEqual(cert_path, cert_path_2)
        self.assertEqual(key_path, key_path_2)
        with open(cert_path_2, "rb") as f:
            self.assertEqual(first_cert_bytes, f.read())
        with open(key_path_2, "rb") as f:
            self.assertEqual(first_key_bytes, f.read())


if __name__ == '__main__':
    unittest.main()
